name: Process Data

on:
  workflow_dispatch:
    inputs:
      subject_folder:
        description: 'Subject folder to process (e.g., sub-sM)'
        required: true
        type: string

jobs:
  process-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash
          rclone --version
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          
      - name: Create virtual environment
        run: |
          echo "Creating virtual environment..."
          python -m venv .venv
          echo "Activating virtual environment..."
          source .venv/bin/activate
          echo "Python path:"
          which python
          echo "Installing pip in virtual environment..."
          curl -sS https://bootstrap.pypa.io/get-pip.py | python
          echo "Installing requirements..."
          pip install -r requirements.txt
          
      - name: Configure rclone
        run: |
          mkdir -p ~/.config/rclone
          echo "${{ secrets.RCLONE_CONFIG }}" > ~/.config/rclone/rclone.conf
          chmod 600 ~/.config/rclone/rclone.conf
          
      - name: Sync data from Dropbox
        run: |
          source .venv/bin/activate
          echo "Syncing data from Dropbox..."
          rclone sync dropbox:raw_data/ raw_data/ --progress
          
      - name: Process data
        run: |
          source .venv/bin/activate
          echo "Processing data..."
          python preprocess.py ${{ github.event.inputs.subject_folder }}
          python calculate_metrics.py ${{ github.event.inputs.subject_folder }}
          python generate_flags.py ${{ github.event.inputs.subject_folder }}
          
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: processed-data
          path: |
            results/
            preprocessed_data/
          if-no-files-found: error 