name: Process Data

on:
  workflow_dispatch:
    inputs:
      subject_folder:
        description: 'Subject folder to process (e.g., sub-sM)'
        required: true
        type: string
  push:
    branches:
      - main
    paths:
      - '.github/workflows/process_data.yml'
      - 'requirements.txt'
      - 'preprocess.py'
      - 'calculate_metrics.py'
      - 'generate_flags.py'

jobs:
  process-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash
          rclone --version
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          
      - name: Create virtual environment
        run: |
          echo "Creating virtual environment..."
          python -m venv .venv
          echo "Activating virtual environment..."
          source .venv/bin/activate
          echo "Python path:"
          which python
          echo "Installing pip in virtual environment..."
          curl -sS https://bootstrap.pypa.io/get-pip.py | python
          echo "Installing requirements..."
          pip install -r requirements.txt
          
      - name: Configure rclone
        run: |
          echo "Setting up rclone configuration..."
          mkdir -p ~/.config/rclone
          echo "${{ secrets.RCLONE_CONFIG }}" | base64 -d > ~/.config/rclone/rclone.conf
          chmod 600 ~/.config/rclone/rclone.conf
          
          echo "Verifying rclone configuration..."
          echo "Configuration file exists:"
          ls -l ~/.config/rclone/rclone.conf
          echo "Configuration file contents (without sensitive data):"
          grep -v "token" ~/.config/rclone/rclone.conf
          echo "Available remotes:"
          rclone listremotes
          
      - name: Test Dropbox connection
        run: |
          echo "Testing Dropbox connection..."
          rclone lsd rdoc_dropbox: || {
            echo "Error: Could not list Dropbox root directory"
            exit 1
          }
          echo "Successfully connected to Dropbox"
          
      - name: Create directory structure
        run: |
          echo "Creating required directories..."
          mkdir -p preprocessed_data
          mkdir -p raw_data
          mkdir -p results/metrics
          mkdir -p output
          echo "Directory structure created:"
          tree -L 2
          
      - name: Sync data from Dropbox
        run: |
          source .venv/bin/activate
          echo "Syncing data from Dropbox..."
          rclone sync rdoc_dropbox:rdoc_fmri_behavior/output/raw/ raw_data/ --progress
          
      - name: Process data
        run: |
          source .venv/bin/activate
          echo "Processing data..."
          # For push events, process all subjects
          if [ "${{ github.event_name }}" = "push" ]; then
            echo "Processing all subjects..."
            python preprocess.py
            python calculate_metrics.py
            python generate_flags.py
          else
            # For manual triggers, process specific subject
            python preprocess.py ${{ github.event.inputs.subject_folder }}
            python calculate_metrics.py ${{ github.event.inputs.subject_folder }}
            python generate_flags.py ${{ github.event.inputs.subject_folder }}
          fi
          
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: processed-data
          path: |
            results/
            preprocessed_data/
          if-no-files-found: error 